#!/usr/bin/env node

const lightify = require('node-lightify');
const config = require('./config.json');
const { resolve } = require('path');
const { readFileSync } = require('fs');

const chilliFile = resolve(__dirname, '../chili.json');
const connection = new lightify.lightify(config.lightify);

function check({ status, friendlyMac }) {
   const { temperature } = JSON.parse(readFileSync(chilliFile).toString());
   const { max, min } = config.temperature;
   if (temperature > max && status) {
     // turn off
     console.log(`current temperature of ${temperature}°C is too high (max: ${max})`);
     return connection.nodeOnOff(friendlyMac, 0);
   } else if (temperature < min && !status) {
     // turn on
     console.log(`current temperature of ${temperature}°C is too low (min: ${min})`);
     return connection.nodeOnOff(friendlyMac, 1);
   }
}

connection.connect()
  .then(() => connection.discover())
  .then(data => data.result
    .find(entry => entry.friendlyMac === config.heatingMac))
  .then(data => check(data))
  .then(() => connection.dispose())
  .catch((error) => {
    console.error('error', error);
    connection.dispose();
});
