#!/usr/bin/env node

 const lightify = require('node-lightify');
 const config = require('./config.json');

 const connection = new lightify.lightify(config.lightify);
 connection.connect()
  .then(() => connection.discover())
  .then(data => {
    console.log(data.result);
  })
  .then(() => connection.dispose())
  .catch((error) => {
    console.error('error', error);
    connection.dispose();
  });
