#!/usr/bin/env node

 const lightify = require('node-lightify');
 const config = require('./config.json');

 const connection = new lightify.lightify(config.lightify);
 connection.connect()
  .then(() => connection.discover())
  .then(data => {data.result
    .find(entry => entry.friendlyMac === config.heatingMac))
  .then((data) => {
    if (data) {
      const status = !(data.status === 1);
      return connection.nodeOnOff(data.friendlyMac, status)
    }
  }})
  .then(() => connection.dispose())
  .catch((error) => {
    console.error('error', error);
    connection.dispose();
  });
